---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    analysis_meteohydro_sfc_rtma_time:
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:analysis_meteohydro_sfc_rtma_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: after
                        gml:timeInterval: 60
          gmd:descriptiveKeywords__gcmd_place: [
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA",
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA > ALASKA",
            "OCEAN > PACIFIC OCEAN > WESTERN PACIFIC OCEAN > MICRONESIA > GUAM",
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA > HAWAII",
            "OCEAN> ATLANTIC OCEAN> NORTH ATLANTIC OCEAN> CARIBBEAN SEA> PUERTO RICO",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'meteorology',
            'hydrology',
            'synopticMeteorology',
            'marineMeteorology'
          ]
        gmd:distributionInfo:
          gmd:MD_Distribution: 
            gmd:transferOptions:
              gmd:MD_DigitalTransferOptions:
                gmd:onLine__xlink:title__NOAA_GeoPlatform_Entry:
                  gmd:CI_OnlineResource:
                    gmd:linkage:
                      gmd:URL: 'http://noaa.maps.arcgis.com/home/item.html?id=1e0827df672b45f4987ce471b15dc792'
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The source files are in GRIB2 format.
                gmd:statement: >
                  This data is generated from the latest analyses from the production suite
                  at NCEP.

