---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    analysis_ocean_sfc_sst_time:
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:analysis_ocean_sfc_sst_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: after
                        gml:timeInterval: 720
          gmd:descriptiveKeywords__gcmd_place: [
            'OCEAN > ATLANTIC OCEAN',
            'OCEAN > PACIFIC OCEAN',
            'OCEAN > INDIAN OCEAN',
            'OCEAN > ARCTIC OCEAN',
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'meteorology',
            'hydrology',
            'synopticMeteorology',
            'marineMeteorology'
          ]
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The RTGSST source files are in GRIB2 format.  The SPoRT
                  source files are in GeoTIFF format.
                gmd:statement: >
                  The NWS/NCEP daily SST (1/12 deg) analysis is
                  generated by the NCEP RTG_SST Analysis System using a
                  two-dimensional variational interpolation scheme. The
                  interpolation scheme uses the most recent 24-hours
                  buoy and ship data and U.S. Navy SEATEMP (SST)
                  retrievals derived from AVHRR data from the NOAA
                  polar orbiting satellites. The first guess for the
                  interpolation scheme is provided by the un-smoothed
                  analysis from the previous day with a one-day climate
                  adjustment. The analysis system was developed by the
                  NWS/NCEP/Environmental Modeling Center/Marine Modeling
                  and Analysis Branch.
                                                                                
                  The NASA/SPoRT experimental SST Composite is a blend
                  of the MODIS and NESDIS SST products except over the
                  Great Lakes, where it is a blend of the MODIS and
                  the United Kingdom Met Office (UKMO) Operational Sea
                  Surface Temperature and Sea Ice Analysis (OSTIAS2). The
                  NESDIS and OSTIAS2 products have spatial resolutions
                  of 9 and 6 km, respectively. The compositing algorithm
                  uses a seven-day collection of MODIS level-2B data
                  and the most recent NESDIS GOES/POES SST Composite
                  and OSTIAS2 daily products. Two types of weighting
                  are used in the compositing process. One weight is
                  for the data latency and the other for the product
                  type. The MODIS data with a 1-km resolution is given
                  the most weight. All available confidence flags and
                  bias information are incorporated in the compositing
                  process. The SST Composite is computed twice-daily
                  (nighttime and daytime). The MODIS and OSTIA products
                  are obtained in near-real-time from the GHRSST archive
                  at NASA/JPL. The compositing system was developed by
                  NASA Short-Term Prediction Research and Transition
                  Center (SPoRT) Team.

                gmd:processStep: [
                  'The ingest process for RTGSST involves converting
                  from GRIB2 to GeoTIFF and reprojecting to Web Mercator
                  (EPSG:3857). However, because the analysis is global,
                  several problems have been encountered. Data gaps
                  have been produced around the international dateline,
                  problems with ArcGIS have arisen when the web mercator
                  imagery goes beyond +/- 88 degrees North/South, and x/y
                  pixel resolution has produced noticeable inconsistency
                  with the source data. To mitigate these problems,
                  the following procedure was developed.',

                  'Convert GRIB2 message to *.flt/*.hdr (floating point
                  raster).',

                  'Reproject *.flt/*.hdr raster to GeoTIFF in Web
                  Mercator, using a chosen x and y pixel resolution that
                  produces usable output.',

                  'Crop extent of raster to approximately +/- 88 degrees
                  North/South (using meter coordinates), which is within
                  the range supported by ArcGIS.',

                  'Clip land areas (set to NoData) using GDAL and an
                  oceans polygon shapefile.',

                  'Generate overviews using gdaladdo to speed up
                  performance at small scales.',

                  'The source files for SPoRT contain 8-bit  unsigned
                  integer (byte) pixel values representing unscaled
                  sea surface temperature values. Once retrieved,
                  the GeoTIFFs are rescaled to 32-bit Floating Point
                  GeoTIFFs representing SST in degrees Fahrenheit,
                  assigned a NoData value, and are reprojected to Web
                  Mercator before cataloging in the Mosaic Dataset.',

                  'The time coverage start of the SPoRT rasters is set to
                  valid time minus the update frequency (e.g. 12 hours).',

                  'The time coverage end time of the SPoRT rasters
                  is set to valid time plus a decided number of
                  minutes. The number of minutes to add should be at
                  least equal to product_delay + script_run_time +
                  script_update_frequency.'
                ]
