---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    analysis_meteohydro_sfc_qpe_time:
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:analysis_meteohydro_sfc_qpe_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: now
                        gml:endPosition: after
                        gml:timeInterval: 4
          gmd:descriptiveKeywords__gcmd_place: [
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'meteorology',
            'hydrology',
            'synopticMeteorology',
            'marineMeteorology'
          ]
        gmd:distributionInfo:
          gmd:MD_Distribution: 
            gmd:transferOptions:
              gmd:MD_DigitalTransferOptions:
                gmd:onLine__xlink:title__NOAA_GeoPlatform_Entry:
                  gmd:CI_OnlineResource:
                    gmd:linkage:
                      gmd:URL: 'http://noaa.maps.arcgis.com/home/item.html?id=2b65b91dcfce4dddb235c61f62dc890d'
                gmd:onLine__references:
                  -
                    gmd:name: 'MRMS - NSSL DEV'
                    gmd:URL: 'http://nmq.ou.edu/'
                  -
                    gmd:name: 'Multi-Radar / Multi-Sensor System (MRMS)'
                    gmd:URL: 'http://www.nssl.noaa.gov/projects/mrms'
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The source files are in GRIB2 format, which contain
                  pixel values representing the precipitation amount
                  in millimeters.
                gmd:statement: >
                  This data is generated from the latest qualitative
                  precipitation estimate outputs in NWS operations at
                  NOAA Integrated Dissemination Program.
                gmd:processStep: [
                  'The rasters are rescaled using GDAL to convert to
                  inches, then reprojected into Web Mercator for storage
                  and inclusion in map services.',

                  'The start time of each accumulation is equal to valid
                  time minus the accumulation period (e.g., a  1-hour
                  QPE valid at 1400 UTC has a start time of 1300 UTC).',

                  'The end time is equal to valid time plus a decided
                  number of minutes.  The number of minutes to add should
                  be at least equal to the product delay + the script
                  run time + the script update frequency.',
                ]
