---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    forecast_meteoceanhydro_pts_zones_geolinks:
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:forecast_meteoceanhydro_pts_zones_geolinks
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
          gmd:descriptiveKeywords__gcmd_place: [
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN",
            "OCEAN > PACIFIC OCEAN > NORTH PACIFIC OCEAN",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > GULF OF MEXICO",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > CARIBBEAN SEA",
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA > GREAT LAKES",
            "OCEAN > PACIFIC OCEAN > NORTH PACIFIC OCEAN > BERING SEA",
            "OCEAN > PACIFIC OCEAN > NORTH PACIFIC OCEAN > GULF OF ALASKA",
            "OCEAN > PACIFIC OCEAN > WESTERN PACIFIC OCEAN > MICRONESIA > GUAM",
          ]
