---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    guidance_model_coastalocean_estofs_time:
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:guidance_model_coastalocean_estofs_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: after
                        gml:timeInterval: 360
          gmd:descriptiveKeywords__gcmd_place: [
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > GULF OF MEXICO",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > CARIBBEAN SEA > PUERTO RICO",
            "OCEAN > PACIFIC OCEAN > NORTH PACIFIC OCEAN",
            "OCEAN > PACIFIC OCEAN > CENTRAL PACIFIC OCEAN > HAWAIIAN ISLANDS",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'hydrology',
            'oceanography']
          ]
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  ESTOFS output files are in GRIB2 format.
                gmd:statement: >
                  This data derives from ESTOFS model runs originating
                  from the NOAA Weather and Climate Operational
                  Supercomputer System (WCOSS), operated by NCEP Central
                  Operations.
                gmd:processStep: [
                  'Each forecast projection for each region is exported
                  from a GRIB2 message to a *.flt/*.hdr (floating point
                  raster).',

                  'The projection is then then reprojected to Web Mercator
                  (EPSG:3857) in GeoTIFF format. The pixel values of the
                  final GeoTIFFs represent actual water level values in
                  feet; thus, users can perform identify operations on
                  the map service(s) to obtain raw data values at any
                  geographic point.'
                ]
