---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    guidance_model_coastalocean_nwgofs_time:
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:guidance_model_coastalocean_nwgofs_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: after
                        gml:timeInterval: 360
          gmd:descriptiveKeywords__gcmd_place: [
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > GULF OF MEXICO",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'hydrology',
            'oceanography']
          ]
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  NGOFS output files are in netCDF format.
                gmd:statement: >
                  This data derives from FVCOM model runs on the NOAA
                  Weather and Climate Operational Supercomputer System
                  (WCOSS) operated by NCEP Central Operations.
                gmd:processStep: [
                  'The flowVis2D visualization software package is used
                  to generate GeoTIFFs of surface current, salinity,
                  temperature, and water level data from each of the
                  supported OFSs. For each model being processed, a series
                  of GeoTIFFs are produced for each forecast projection;
                  one at the maximum desired resolution/level-of-detail
                  along with zero or more overviews, which are used to
                  display an appropriate amount of detail at any scale.'
                ]
