---
project: IDP-GIS
server: idpgis.ncep.noaa.gov
folder:
  -
    name: NWS_Climate_Outlooks
    service:
      -
        name: cpc_6_10_day_outlk
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_8_14_day_outlk
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_cmorph_dly_025deg
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:abstract: >
                CMORPH (CPC MORPHing technique) produces global
                precipitation analyses at very high spatial and temporal
                resolution. This technique uses precipitation estimates
                that have been derived from low orbiter satellite
                microwave observations exclusively, and whose features
                are transported via spatial propagation information that
                is obtained entirely from geostationary satellite IR
                data. At present we incorporate precipitation estimates
                derived from the passive microwaves aboard the DMSP 13,
                14 & 15 (SSM/I), the NOAA-15, 16, 17 & 18 (AMSU-B), and
                AMSR-E and TMI aboard NASA's Aqua and TRMM spacecraft,
                respectively. These estimates are generated by algorithms
                of Ferraro (1997) for SSM/I, Ferraro et al. (2000) for
                AMSU-B and Kummerow et al. (2001) for TMI. Note that this
                technique is not a precipitation estimation algorithm
                but a means by which estimates from existing microwave
                rainfall algorithms can be combined. Therefore, this
                method is extremely flexible such that any precipitation
                estimates from any microwave satellite source can
                be incorporated. With regard to spatial resolution,
                although the preciptation estimates are available
                on a grid with a spacing of 8 km (at the equator),
                the resolution of the individual satellite-derived
                estimates is coarser than that - more on the order of
                12 x 15 km or so. The finer "resolution" is obtained via
                interpolation. In effect, IR data are used as a means to
                transport the microwave-derived precipitation features
                during periods when microwave data are not available at
                a location. Propagation vector matrices are produced
                by computing spatial lag correlations on successive
                images of geostationary satellite IR which are then
                used to propagate the microwave derived precipitation
                estimates. This process governs the movement of the
                precipitation features only. At a given location, the
                shape and intensity of the precipitation features in
                the intervening half hour periods between microwave
                scans are determined by performing a time-weighting
                interpolation between microwave-derived features that
                have been propagated forward in time from the previous
                microwave observation and those that have been propagated
                backward in time from the following microwave scan. We
                refer to this latter step as "morphing" of the features.
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_drought_outlook
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_gfs_precip_anom
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_mthly_precip_anom
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_mthly_temp_outlk
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
              gmd:abstract: >
                A CPC forecaster creates the monthly temperature
                outlooks. Shading starts at 33%, with contours at 33%,
                40%, 50%, 60%, 70%, 80% and 90%. The shaded areas in
                outlooks are of probabilities of above or below normal
                temperature. Any area not specifically colored on the map
                delineate areas where there is little no climate signal,
                so the chances for above, near, and below are equal
                (formally termed Equal Chances). The forecast valid
                period is the next calendar month.
      -
        name: cpc_sea_precip_outlk
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_sea_temp_outlk
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
      -
        name: cpc_weather_hazards
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
              gmd:abstract: >
                Temperature, precipitation, flooding, high winds, high
                waves, and wildfire/drought hazards for the U.S. through
                14 days.
      -
        name: cpc_wkly_sst
        gmi:MI_Metadata:
          gmd:fileIdentifier: gov.noaa.nws.idpgis
          gmd:identificationInfo:
            srv:SV_ServiceIdentification:
              gmd:citation:
                gmd:CI_Citation:
                    gmd:date__creation: 2016-07-07
                    gmd:date__publication:  2016-07-07
