---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    service: radar_meteo_imagery_nexrad_time
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:radar_meteo_imagery_nexrad_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: now
                        gml:timeInterval: 2
          gmd:descriptiveKeywords__gcmd_place: [
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA",
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA > ALASKA",
            "OCEAN > PACIFIC OCEAN > WESTERN PACIFIC OCEAN > MICRONESIA > GUAM",
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA > HAWAII",
            "OCEAN> ATLANTIC OCEAN> NORTH ATLANTIC OCEAN> CARIBBEAN SEA> PUERTO RICO",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherObservations',
            'meteorology',
            'synopticMeteorology']
          ]
        gmd:distributionInfo:
          gmd:MD_Distribution: 
            gmd:transferOptions:
              gmd:MD_DigitalTransferOptions:
                gmd:onLine__xlink:title__NOAA_GeoPlatform_Entry:
                  gmd:CI_OnlineResource:
                    gmd:linkage:
                      gmd:URL: 'http://noaa.maps.arcgis.com/home/item.html?id=da53700b1f324cc685c4d3bcc00c12fc'
                gmd:onLine__references:
                  -
                    gmd:name: >
                      'A Physically Based Precipitation–Nonprecipitation
                      Radar Echo Classifier Using Polarimetric and
                      Environmental Data in a Real-Time National System'
                    gmd:URL: 'http://journals.ametsoc.org/doi/full/10.1175/WAF-D-13-00072.1'
                  -
                    gmd:name: 'Radar Images for GIS Software'
                    gmd:URL: 'http://www.srh.noaa.gov/jetstream/doppler/gis.htm'
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The source files are in GRIB2 format.
                gmd:statement: >
                  The source of the base reflectivity mosaics is
                  the NOAA Multi-Radar/Multi-Sensor (MRMS) System,
                  which is developed by the NOAA National Severe Storms
                  Laboratory (NSSL) and operated by NWS/National Centers
                  for Environmental Prediction (NCEP) Central Operations
                  (NCO).
                gmd:processStep: [
                  'The QPE GeoTIFF source files contain pixel values
                  representing the actual precipitation amount in
                  1/100 inch units. The QPE GRIB2 source files contain
                  pixel values representing the precipitation amount in
                  millimeters. These rasters are rescaled using GDAL to
                  convert to inches.',

                  'The rasters are then reprojected into Web Mercator
                  for storage and inclusion in map services.',

                  'The time coverage start time of each QPE accumulation
                  period is set to valid time minus the accumulation
                  period (e.g., a 1-hour QPE valid at 1400 UTC has a
                  start time of 1300 UTC).',

                  'The time coverage end time is set to valid time plus
                  a decided number of minutes. The number of minutes
                  to add should be at least equal to: product_delay +
                  script_run_time + script_update_frequency.',
                ]

