---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    service: wwa_meteocean_tropicalcyclones_inundation
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:wwa_meteocean_tropicalcyclones_inundation
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:abstract: >
              This nowCOAST map service provides maps depicting the
              latest official NWS Potential Storm Surge Flooding Map
              for any significant landfalling tropical cyclone expected
              to impact the Atlantic or Gulf of Mexico Coasts of the
              Contiguous United States. The map layers depict the risk
              associated with coastal flooding from storm surge associated
              with tropical cyclones.

              The Potential Storm Surge Flooding Map depicts the
              geographical areas where inundation from storm surge could
              occur along with the heights, above ground, that water
              could reach in those areas. These potential heights are
              represented with different colors based on water level:
              1) Greater than 1 foot above ground (blue), 2) Greater
              than 3 feet above ground (yellow), 3) Greater than 6 feet
              above ground (orange), and 4) Greater than 9 feet above
              ground (red). Two versions of this graphic are provided in
              this map--one with a mask (depicted in gray) identifying
              Intertidal Zone/Estuarine Wetland areas, and another version
              without the mask where Intertidal Zone/Estuarine Wetland
              areas are symbolized with the same colors as other areas.

              Two additional layers are provided to depict 1) the full
              geographic extent for which the Potential Storm Surge
              Flooding Map is presently valid (the "map boundary"),
              and 2) Levee Areas, if any, within the affected area
              (symbolized with a black-and-white diagonal hatch pattern).

              If the Potential Storm Surge Flooding Map is not presently
              active, all layers will be blank except for the Map Boundary
              layer, which will display a shaded region indicating the
              coverage area for any potential future graphics along
              with a text label indicating that the map is not presently
              available.

              This map service is updated approximately every 10 minutes
              on nowCOAST to ensure the latest information is provided
              to the user as soon as it becomes available. Once issued,
              the Potential Storm Surge Flooding Map will be updated
              by NHC every six hours alongside each new Forecast
              Advisory for the associated tropical cyclone. However,
              due to processing requirements during the creation of this
              product, the flooding map becomes available approximately
              60 to 90 minutes following the release of the associated
              NHC Forecast Advisory, at which point nowCOAST will
              acquire it and update this map service within the next
              10 to 20 minutes (i.e., this product will be updated on
              nowCOAST within approximately 70 to 110 minutes after the
              associated Forecast Advisory is released). For more detailed
              information about layer update frequency and timing,
              please reference the nowCOAST Dataset Update Schedule.

              Background Information: Developed by National Hurricane
              Center (NHC) over the course of several years in
              consultation with social scientists, emergency managers,
              broadcast meteorologists, and others, the Potential Storm
              Surge Flooding Map is intended to depict the risk associated
              with coastal flooding from storm surge associated with
              tropical cyclones. On June 1, 2016 it became an operational
              product, issued on demand for certain tropical cyclones
              that are expected to affect the Atlantic and Gulf Coasts
              of the United States. The product is not available for
              tropical cyclones that may affect coastal areas in the
              Eastern or Central Pacific regions.

            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2016-09-13
                gmd:date__publication:  2016-09-13
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: now
                        gml:timeInterval: 15
          gmd:descriptiveKeywords__gcmd_place: [
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > GULF OF MEXICO",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > CARIBBEAN SEA",
          ]
        gmd:distributionInfo:
          gmd:MD_Distribution: 
            gmd:transferOptions:
              gmd:MD_DigitalTransferOptions:
                gmd:onLine__xlink:title__NOAA_GeoPlatform_Entry:
                  gmd:CI_OnlineResource:
                    gmd:linkage:
                      gmd:URL: 'http://noaa.maps.arcgis.com/home/item.html?id=da53700b1f324cc685c4d3bcc00c12fc'
                gmd:onLine__references:
                  -
                    gmd:name: >
                      NHC, 2016: Potential Storm Surge Flooding Map,
                      NWS/NCEP National Hurricane Center, Miami, FL
                    gmd:URL: 'http://www.nhc.noaa.gov/surge/inundation/'
                  -
                    gmd:name: >
                      NWS, 2016: Potential Storm Surge Flooding Map
                      Product Description Document, NWS, Silver Spring, MD
                    gmd:URL: 'http://www.nhc.noaa.gov/pdf/PDD-PotentialStormSurgeFloodingMap.pdf'
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The source files are in shapefile format.
                gmd:statement: >
                  The shapefiles are obtained from NCO, who obtains them
                  from NWS/National Hurricane Center (NHC).

