---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    service: wwa_meteocean_tropicalcyclones_trackintensityfcsts_time
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:wwa_meteocean_tropicalcyclones_trackintensityfcsts_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: now
                        gml:timeInterval: 15
          gmd:descriptiveKeywords__gcmd_place: [
            "OCEAN > PACIFIC OCEAN > EASTERN PACIFIC OCEAN",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > GULF OF MEXICO",
            "OCEAN > ATLANTIC OCEAN > NORTH ATLANTIC OCEAN > CARIBBEAN SEA",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'meteorology',
            'synopticMeteorology'
          ]
        gmd:distributionInfo:
          gmd:MD_Distribution: 
            gmd:transferOptions:
              gmd:MD_DigitalTransferOptions:
                gmd:onLine__xlink:title__NOAA_GeoPlatform_Entry:
                  gmd:CI_OnlineResource:
                    gmd:linkage:
                      gmd:URL: 'http://noaa.maps.arcgis.com/home/item.html?id=10dc113cdf7f46f5878ebae4a7c5d708'
                gmd:onLine__references:
                  -
                    gmd:name: >
                      CPHC, 2015: Tropical Cyclone Product Help, NWS/CPHC,
                      Honolulu, HI
                    gmd:URL: 'http://www.prh.noaa.gov/cphc/pages/abouttcprod.php'
                  -
                    gmd:name: >
                      NHC, 2015: NHC Data in GIS Formats, NWS/NCEP
                      National Hurricane Center, Miami, FL
                    gmd:URL: 'http://www.nhc.noaa.gov/gis'
                  -
                    gmd:name: >
                      NWS, 2013: NWS Instructions 10-601, Tropical
                      Cyclone Products, NWS, Silver Spring, MD
                    gmd:URL: 'http://www.nws.noaa.gov/directives/'
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The source files are in shapefile format.
                gmd:statement: >
                  The shapefiles are obtained from NCO, who obtains them
                  from NWS/National Hurricane Center (NHC).
                gmd:processStep: [
                  'The NHC and CPHC maintain several RSS "wallets"
                  (five for the Atlantic, five for the Eastern Pacific,
                  and five for the Central Pacific), any of which
                  can contain information about a Tropical Cyclone
                  Advisory at any time. If each of these feeds are
                  empty, it indicates that there are no active Tropical
                  Cyclones in either basin at the present time, in which
                  case care is taken to erase all features currently
                  stored in the database. However, for each wallet
                  that contains information about an active system,
                  several pieces of information must be parsed from
                  the RSS file, including advisory issuance time, URL
                  to the public advisory bulletin, name/number/basin of
                  storm, and links to the 5-Day Track Forecast/Cone of
                  Uncertainty/Watches and Warnings, Best Track (if any),
                  and Forecast Information ZIP archives. Each of these
                  archives contains a series of polygon, point and/or
                  line shapefiles that must be ingested.',

                  'Because the map service that hosts these datasets
                  is time-enabled, care must also be taken to correctly
                  attribute time information. While time information may
                  not be extremely critical for these products (since
                  there will only be one set of data for each storm),
                  the service is time-enabled mainly for consistency
                  with other time-aware datasets, and because it affords
                  flexibility in the future if it is wished to archive
                  past track forecasts. Presently, the start time of
                  all features related to an advisory is set to the
                  advisory issuance time, while the end time is set to
                  5 days in the future (to correspond with the 5-day
                  advisory horizon).',
                ]        

