---
project: nowCOAST
server: nowcoast.ncep.noaa.gov
services:
  nowcoast:
    service: wwa_meteoceanhydro_longduration_hazards_time
      gmi:MI_Metadata:
        gmd:fileIdentifier: gov.noaa.nos.ocs.nowcoast:wwa_meteoceanhydro_longduration_hazards_time
        gmd:identificationInfo:
          srv:SV_ServiceIdentification:
            gmd:citation:
              gmd:CI_Citation:
                gmd:date__creation:  2015-09-21
                gmd:date__publication:  2015-09-21
            srv:extent:
              gmd:EX_Extent:
                gmd:temporalElement:
                  gmd:EX_TemporalExtent:
                    gmd:extent:
                      gml:TimePeriod:
                        gml:beginPosition: before
                        gml:endPosition: now
                        gml:timeInterval: 10
          gmd:descriptiveKeywords__gcmd_place: [
            "CONTINENT > NORTH AMERICA > UNITED STATES OF AMERICA",
          ]
          gmd:descriptiveKeywords__wmo_theme: [
            'weatherForecasts',
            'meteorology',
          ]
        gmd:distributionInfo:
          gmd:MD_Distribution: 
            gmd:transferOptions:
              gmd:MD_DigitalTransferOptions:
                gmd:onLine__xlink:title__NOAA_GeoPlatform_Entry:
                  gmd:CI_OnlineResource:
                    gmd:linkage:
                      gmd:URL: 'http://noaa.maps.arcgis.com/home/item.html?id=3c780d2934024873b6046d4a4eee806a'
        gmd:dataQualityInfo:
          gmd:DQ_DataQuality:
            gmd:lineage:
              gmd:LI_Lineage:
                gmd:source: >
                  The source files are in text bulletin format and
                  shapefile format.
                gmd:statement: >
                  The shapefiles and text bulletings are obtained from
                  the National Weather Service.
                gmd:processStep: [
                  'There are two main types of wwa''s currently processed
                  here: "hazards" and "warnings", which reflect the naming
                  conventions of the NWS Southern Region Headquarters
                  (SRH) data providers.',

                  'The warnings dataset consists of short-duration
                  warnings including Severe Thunderstorm, Flash Flood,
                  Special Marine, Extreme Wind, and Tornado Warnings.',

                  'The hazards dataset consists of all other
                  watch/warning/advisory types (both short- and
                  long-duration).',

                  'In addition to the primary hazards and warnings
                  datasets produced by NWS SRH, Coastal and Offshore
                  hazards for Alaska are processed separately by parsing
                  the text forecasts for each zone. This is required
                  because the SRH dataset is derived from VTEC and Alaska
                  WFOs do not use VTEC for marine WWAs.',

                  'In order to combine both sets of hazards, it is assumed
                  that the Alaska hazards are kept up-to-date by parsing
                  the text forecasts on a set schedule and storing the
                  results in its own tables (one for coastal and one for
                  offshore Alaska WWAs). Then, when the primary (SRH)
                  hazards product is updated, any features present in the
                  Alaska tables will be pulled in to the primary table.',

                  'Because the warnings table only handles five
                  types of WWAs and there are never more than
                  a handful of active short-duration warnings at
                  any time, no additional processing is done on the
                  warnings dataset after importing and minor dataset
                  cleaning/repairing. Conversely, the hazards dataset
                  can be quite large, as often much of the U.S. is
                  covered in one or more hazards and split into separate
                  polygon features for each zone/WWA combination. For
                  this reason, some extra processing is performed to
                  the hazards dataset to ensure adequate performance in
                  a map service.',

                  'After all new features have been imported into the
                  primary hazards table and old features have been
                  removed, hazards are split into individual tables
                  using a categorical classification (e.g., maritime wind
                  hazards, inland wind hazards, coastal flooding hazards,
                  inland flooding hazards, snow/freezing precipitation
                  hazards, etc.), each category being picked such
                  that they can be grouped together in a single map
                  layer. This not only improves performance by ensuring
                  spatial indexes are managable and efficient, but also
                  allows for the priority of each category to be adjusted
                  in relation to one another, i.e. more important WWA
                  categories can appear on top of less important ones.',

                  'Once the categorical tables have been updated,
                  each table is then postprocessed with a "dissolve"
                  operation to merge adjacent WWAs of the same type and
                  time attributes. By performing a dissolve, many of
                  the vertices present in the old polygons are dropped
                  in favor of a single large polygon that covers the
                  footprint of the original features. This is mainly done
                  to improve performance of the map service, but can
                  also improve graphical representation by not drawing
                  the boundaries between zones and instead focusing on
                  the entire WWA coverage area. However, the problem
                  with the dissolve operation is that it does not allow
                  unique attributes of each source polygon to be extracted
                  into the dissolved table, which means that attributes
                  like individual hazard URLs must be dropped. For this
                  reason, and also because performance of the original
                  categorical tables is often adequate, the dissolved
                  tables are not presently used in the map services.'

                ]        

