"""
More or less constant values.  Only needs to be updated when a service gets
added or dropped.
"""
nowcoast_services = [
    'nowcoast/radar_meteo_imagery_nexrad_time',
    'nowcoast/wwa_meteocean_tropicalcyclones_trackintensityfcsts_time',
    'nowcoast/wwa_meteocean_tropicalcyclones_inundation',
    'nowcoast/wwa_meteoceanhydro_shortduration_hazards_warnings_time',
    'nowcoast/wwa_meteoceanhydro_longduration_hazards_time',
    'nowcoast/wwa_meteoceanhydro_shortduration_hazards_watches_time',
    'nowcoast/guidance_model_coastalocean_cbofs_offsets',
    'nowcoast/sat_meteo_imagery_goes_time',
    'nowcoast/guidance_model_coastalocean_sjrofs_offsets',
    'nowcoast/guidance_model_coastalocean_creofs_offsets',
    'nowcoast/guidance_model_coastalocean_dbofs_offsets',
    'nowcoast/guidance_model_coastalocean_sfbofs_offsets',
    'nowcoast/guidance_model_coastalocean_ngofs_offsets',
    'nowcoast/guidance_model_coastalocean_tbofs_offsets',
    'nowcoast/obs_meteocean_insitu_sfc_time',
    'nowcoast/guidance_model_greatlakes_lhofs_offsets',
    'nowcoast/guidance_model_greatlakes_lmofs_offsets',
    'nowcoast/guidance_model_greatlakes_lsofs_offsets',
    'nowcoast/guidance_model_greatlakes_loofs_offsets',
    'nowcoast/guidance_model_ocean_grtofs_offsets',
    'nowcoast/guidance_model_greatlakes_leofs_offsets',
    'nowcoast/guidance_model_coastalocean_nyofs_offsets',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_time',
    'nowcoast/analysis_meteohydro_sfc_qpe_time',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_qpf6hrs_offsets',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_windvel_offsets',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_windspeed_offsets',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_signwaveht_offsets',
    'nowcoast/forecast_meteoceanhydro_pts_zones_geolinks',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_relhumidity_offsets',
    'nowcoast/mapoverlays_political',
    'nowcoast/sat_meteo_emulated_imagery_lightningstrikedensity_goes_time',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_windgust_offsets',
    'nowcoast/analysis_meteohydro_sfc_rtma_time',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_dailymaxairtemp_offsets',
    'nowcoast/guidance_model_coastalocean_tbofs_time',
    'nowcoast/forecast_meteoceanhydro_sfc_ndfd_dailyminairtemp_offsets',
    'nowcoast/guidance_model_coastalocean_sfbofs_time',
    'nowcoast/guidance_model_coastalocean_sjrofs_time',
    'nowcoast/guidance_model_coastalocean_ngofs_time',
    'nowcoast/guidance_model_coastalocean_dbofs_time',
    'nowcoast/guidance_model_coastalocean_nwgofs_time',
    'nowcoast/guidance_model_coastalocean_creofs_time',
    'nowcoast/guidance_model_coastalocean_negofs_time',
    'nowcoast/guidance_model_coastalocean_cbofs_time',
    'nowcoast/mapoverlays_transportation',
    'nowcoast/guidance_natlcenters_meteoceanhydro_outlooks_time',
    'nowcoast/guidance_model_greatlakes_lsofs_time',
    'nowcoast/guidance_model_greatlakes_loofs_time',
    'nowcoast/guidance_model_greatlakes_lmofs_time',
    'nowcoast/guidance_model_coastalocean_estofs_time',
    'nowcoast/guidance_model_greatlakes_leofs_time',
    'nowcoast/guidance_model_ocean_grtofs_time',
    'nowcoast/guidance_model_greatlakes_lhofs_time',
    'nowcoast/mapoverlays_admin_fedgov',
    'nowcoast/analysis_ocean_sfc_sst_time',
    'nowcoast/obs_meteoceanhydro_insitu_pts_geolinks',
    'nowcoast/guidance_meteoceanhydro_pts_geolinks',
    'nowcoast/guidance_model_coastalocean_nyofs_time',
    'nowcoast/obs_meteoceanhydro_remote_pts_areas_geolinks',
    'nowcoast/forecastdiscussion_meteoceanhydro_zones_geolinks'
]

idpgis_services = [
    'NMFS/EFH_MapperData',
    'NMFS/EFH_Only',
    'NMFS/EFH_Salmon_Data_25m',
    'NMFS/EFHAreasProtectedFromFishing',
    'NMFS/HAPC',
    'NOAA/MPA_Inventory_Fishing',
    'NOAA/MPA_Inventory_Generalized',
    'NOAA/MPA_Inventory_Government_Level',
    'NOAA/MPA_Inventory_National_System',
    'NOAA/MPA_Inventory_ONMS_only',
    'NOAA/MPA_Inventory_Primary_Conservation_Focus',
    'NOAA/MPA_Inventory_Protection_Level',
    'NOAA/MPA_Inventory',
    'NOAA/NOAA_Estuarine_Bathymetry',
    'NOAA/NOAA_Medium_Resolution_Shoreline',
    'NOS_Biogeo_Biomapper/AS_Dynamic',
    'NOS_Biogeo_Biomapper/AS_Imagery',
    'NOS_Biogeo_Biomapper/Biogeo_BenthicHabitat',
    'NOS_Biogeo_Biomapper/BUIS_Dynamic',
    'NOS_Biogeo_Biomapper/CNMI_Dynamic',
    'NOS_Biogeo_Biomapper/CNMI_Imagery',
    'NOS_Biogeo_Biomapper/Guam_Dynamic',
    'NOS_Biogeo_Biomapper/Guam_Imagery',
    'NOS_Biogeo_Biomapper/Hawaii_Dynamic',
    'NOS_Biogeo_Biomapper/Hawaii_Imagery',
    'NOS_Biogeo_Biomapper/Jobos_Dynamic',
    'NOS_Biogeo_Biomapper/Jobos_Imagery',
    'NOS_Biogeo_Biomapper/MI_Dynamic',
    'NOS_Biogeo_Biomapper/MI_Imagery',
    'NOS_Biogeo_Biomapper/NER_Dynamic',
    'NOS_Biogeo_Biomapper/NY_Biogeo_Assessment',
    'NOS_Biogeo_Biomapper/Palau_Dynamic',
    'NOS_Biogeo_Biomapper/Palau_Imagery',
    'NOS_Biogeo_Biomapper/Palmyra_Dynamic',
    'NOS_Biogeo_Biomapper/Palmyra_Imagery',
    'NOS_Biogeo_Biomapper/PR_Dynamic',
    'NOS_Biogeo_Biomapper/PR_Imagery',
    'NOS_Biogeo_Biomapper/STEER_Dynamic',
    'NOS_Biogeo_Biomapper/STEER_Imagery',
    'NOS_Biogeo_Biomapper/StJ_Dynamic',
    'NOS_Biogeo_Biomapper/StJ_Imagery',
    'NOS_Biogeo_Biomapper/SWPR_Dynamic',
    'NOS_Biogeo_Biomapper/SWPR_Imagery',
    'NOS_Biogeo_Biomapper/USVI_Dynamic',
    'NOS_Biogeo_Biomapper/USVI_Imagery',
    'NOS_Biogeo_Biomapper/Vieques_Dynamic',
    'NOS_Biogeo_Biomapper/Vieques_Imagery',
    'NOS_Biogeo_Biomapper/WA_MSP',
    'NOS_ESI/ESI_Alabama_Data',
    'NOS_ESI/ESI_Alabama_Maps (ImageServer)',
    'NOS_ESI/ESI_Alabama_TandE_Data',
    'NOS_ESI/ESI_Aleutians_Data',
    'NOS_ESI/ESI_Aleutians_TandE_Data',
    'NOS_ESI/ESI_AmericanSamoa_Data',
    'NOS_ESI/ESI_AmericanSamoa_Maps (ImageServer)',
    'NOS_ESI/ESI_AmericanSamoa_TandE_Data',
    'NOS_ESI/ESI_BristolBay_Data',
    'NOS_ESI/ESI_BristolBay_TandE_Data',
    'NOS_ESI/ESI_CentralCalifornia_Data',
    'NOS_ESI/ESI_CentralCalifornia_Maps (ImageServer)',
    'NOS_ESI/ESI_CentralCalifornia_TandE_Data',
    'NOS_ESI/ESI_ColumbiaRiver_Data',
    'NOS_ESI/ESI_ColumbiaRiver_Maps (ImageServer)',
    'NOS_ESI/ESI_ColumbiaRiver_TandE_Data',
    'NOS_ESI/ESI_CookInlet_Data',
    'NOS_ESI/ESI_CookInlet_TandE_Data',
    'NOS_ESI/ESI_DelawareBay_Data',
    'NOS_ESI/ESI_DelawareBay_Maps (ImageServer)',
    'NOS_ESI/ESI_DelawareBay_TandE_Data',
    'NOS_ESI/ESI_FloridaPanhandle_Data',
    'NOS_ESI/ESI_FloridaPanhandle_TandE_Data',
    'NOS_ESI/ESI_FloridaPeninsular_Data',
    'NOS_ESI/ESI_FloridaPeninsular_TandE_Data',
    'NOS_ESI/ESI_Georgia_Data',
    'NOS_ESI/ESI_Georgia_Maps (ImageServer)',
    'NOS_ESI/ESI_Georgia_TandE_Data',
    'NOS_ESI/ESI_Guam_Data',
    'NOS_ESI/ESI_Guam_Maps (ImageServer)',
    'NOS_ESI/ESI_Guam_TandE_Data',
    'NOS_ESI/ESI_Hawaii_Data',
    'NOS_ESI/ESI_Hawaii_Maps (ImageServer)',
    'NOS_ESI/ESI_Hawaii_TandE_Data',
    'NOS_ESI/ESI_HudsonRiver_Data',
    'NOS_ESI/ESI_HudsonRiver_Maps (ImageServer)',
    'NOS_ESI/ESI_HudsonRiver_TandE_Data',
    'NOS_ESI/ESI_Kodiak_Data',
    'NOS_ESI/ESI_Kodiak_TandE_Data',
    'NOS_ESI/ESI_LongIsland_Data',
    'NOS_ESI/ESI_LongIsland_Maps (ImageServer)',
    'NOS_ESI/ESI_LongIsland_TandE_Data',
    'NOS_ESI/ESI_Louisiana_Data',
    'NOS_ESI/ESI_Louisiana_Maps (ImageServer)',
    'NOS_ESI/ESI_Louisiana_TandE_Data',
    'NOS_ESI/ESI_Maryland_Data',
    'NOS_ESI/ESI_Maryland_Maps (ImageServer)',
    'NOS_ESI/ESI_Maryland_TandE_Data',
    'NOS_ESI/ESI_Mississippi_Data',
    'NOS_ESI/ESI_Mississippi_Maps (ImageServer)',
    'NOS_ESI/ESI_Mississippi_TandE_Data',
    'NOS_ESI/ESI_NorthCarolina_Data',
    'NOS_ESI/ESI_NorthCarolina_Maps (ImageServer)',
    'NOS_ESI/ESI_NorthCarolina_TandE_Data',
    'NOS_ESI/ESI_NorthernCalifornia_Data',
    'NOS_ESI/ESI_NorthernCalifornia_Maps (ImageServer)',
    'NOS_ESI/ESI_NorthernCalifornia_TandE_Data',
    'NOS_ESI/ESI_NorthSlope_Data',
    'NOS_ESI/ESI_NorthSlope_TandE_Data',
    'NOS_ESI/ESI_NorthwestArctic_Data',
    'NOS_ESI/ESI_NorthwestArctic_TandE_Data',
    'NOS_ESI/ESI_PrinceWilliamSound_Data',
    'NOS_ESI/ESI_PrinceWilliamSound_TandE_Data',
    'NOS_ESI/ESI_PuertoRico_Data',
    'NOS_ESI/ESI_PuertoRico_Maps (ImageServer)',
    'NOS_ESI/ESI_PuertoRico_TandE_Data',
    'NOS_ESI/ESI_PugetSound_Data',
    'NOS_ESI/ESI_PugetSound_TandE_Data',
    'NOS_ESI/ESI_RI_CT_NY_NJ_Data',
    'NOS_ESI/ESI_RI_CT_NY_NJ_Maps (ImageServer)',
    'NOS_ESI/ESI_SanFrancisco_Data',
    'NOS_ESI/ESI_SanFrancisco_Maps (ImageServer)',
    'NOS_ESI/ESI_SanFrancisco_TandE_Data',
    'NOS_ESI/ESI_Shoreline_Aggregate',
    'NOS_ESI/ESI_Shoreline_Carto',
    'NOS_ESI/ESI_Shoreline_Most_Sensitive',
    'NOS_ESI/ESI_Shoreline',
    'NOS_ESI/ESI_SouthCarolina_Data',
    'NOS_ESI/ESI_SouthCarolina_Maps (ImageServer)',
    'NOS_ESI/ESI_SouthCarolina_TandE_Data',
    'NOS_ESI/ESI_SoutheastAlaska_Data',
    'NOS_ESI/ESI_SoutheastAlaska_TandE_Data',
    'NOS_ESI/ESI_SouthernCalifornia_Data',
    'NOS_ESI/ESI_SouthernCalifornia_Maps (ImageServer)',
    'NOS_ESI/ESI_SouthernCalifornia_TandE_Data',
    'NOS_ESI/ESI_SouthFlorida_Data',
    'NOS_ESI/ESI_SouthFlorida_Maps (ImageServer)',
    'NOS_ESI/ESI_SouthFlorida_TandE_Data',
    'NOS_ESI/ESI_TexasUpperCoast_Data',
    'NOS_ESI/ESI_TexasUpperCoast_Maps (ImageServer)',
    'NOS_ESI/ESI_TexasUpperCoast_TandE_Data',
    'NOS_ESI/ESI_Virginia_Data',
    'NOS_ESI/ESI_Virginia_Maps (ImageServer)',
    'NOS_ESI/ESI_Virginia_TandE_Data',
    'NOS_ESI/ESI_VirginIslands_Data',
    'NOS_ESI/ESI_VirginIslands_Maps (ImageServer)',
    'NOS_ESI/ESI_VirginIslands_TandE_Data',
    'NOS_ESI/ESI_WesternAlaska_Data',
    'NOS_ESI/ESI_WesternAlaska_TandE_Data',
    'NOS_ESI/ESI_WestFlorida_Maps (ImageServer)',
    'NOS_Observations/CO_OPS_Products (FeatureServer)',
    'NOS_Observations/CO_OPS_Products',
    'NOS_Observations/CO_OPS_Stations (FeatureServer)',
    'NOS_Observations/CO_OPS_Stations',
    'NWS_Climate_Outlooks/cpc_6_10_day_outlk',
    'NWS_Climate_Outlooks/cpc_8_14_day_outlk',
    'NWS_Climate_Outlooks/cpc_cmorph_dly_025deg',
    'NWS_Climate_Outlooks/cpc_drought_outlk',
    'NWS_Climate_Outlooks/cpc_gfs_precip_anom',
    'NWS_Climate_Outlooks/cpc_mthly_precip_outlk',
    'NWS_Climate_Outlooks/cpc_mthly_temp_outlk',
    'NWS_Climate_Outlooks/cpc_sea_precip_outlk',
    'NWS_Climate_Outlooks/cpc_sea_temp_outlk',
    'NWS_Climate_Outlooks/cpc_weather_hazards',
    'NWS_Climate_Outlooks/cpc_wkly_sst',
    'NWS_Forecasts_Guidance_Warnings/natl_fcst_wx_chart',
    'NWS_Forecasts_Guidance_Warnings/NDFD_temp',
    'NWS_Forecasts_Guidance_Warnings/NHC_Atl_trop_cyclones_active',
    'NWS_Forecasts_Guidance_Warnings/NHC_Atl_trop_cyclones',
    'NWS_Forecasts_Guidance_Warnings/NHC_E_Pac_trop_cyclones_active',
    'NWS_Forecasts_Guidance_Warnings/NHC_E_Pac_trop_cyclones',
    'NWS_Forecasts_Guidance_Warnings/rfc_dly_qpe',
    'NWS_Forecasts_Guidance_Warnings/rfc_grid_qpf',
    'NWS_Forecasts_Guidance_Warnings/sig_riv_fld_outlk',
    'NWS_Forecasts_Guidance_Warnings/SPC_wx_outlks',
    'NWS_Forecasts_Guidance_Warnings/watch_warn_adv',
    'NWS_Forecasts_Guidance_Warnings/wpc_qpf',
    'NWS_Observations/ahps_riv_gauges',
    'NWS_Observations/NOHRSC_Snow_Analysis',
    'NWS_Observations/radar_base_reflectivity',
]
